<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.cometd</groupId>
    <artifactId>cometd-project</artifactId>
    <version>8.0.5-SNAPSHOT</version>
  </parent>

  <artifactId>cometd-coverage</artifactId>
  <packaging>pom</packaging>

  <name>CometD :: Coverage</name>
  <description>Compute aggregated test code coverage</description>

  <properties>
    <maven.deploy.skip>true</maven.deploy.skip>
  </properties>

  <dependencies>
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>cometd-distribution</artifactId>
      <version>${project.version}</version>
      <type>pom</type>
    </dependency>
    <dependency>
      <groupId>org.cometd</groupId>
      <artifactId>cometd-demo</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>org.cometd.java</groupId>
      <artifactId>cometd-java-annotation-tests</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>org.cometd.java</groupId>
      <artifactId>cometd-java-client-http-tests</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>org.cometd.java</groupId>
      <artifactId>cometd-java-common</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>org.cometd.java</groupId>
      <artifactId>cometd-java-examples-springboot</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>org.cometd.java</groupId>
      <artifactId>cometd-java-server-common</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>org.cometd.java</groupId>
      <artifactId>cometd-java-server-http-tests</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>org.cometd.java.tests</groupId>
      <artifactId>cometd-java-tests-common</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>org.cometd.java.tests</groupId>
      <artifactId>cometd-java-tests-oort</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>org.cometd.java.tests</groupId>
      <artifactId>cometd-java-tests-spring</artifactId>
      <version>${project.version}</version>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.jacoco</groupId>
        <artifactId>jacoco-maven-plugin</artifactId>
        <executions>
          <execution>
            <id>report-aggregate</id>
            <goals>
              <goal>report-aggregate</goal>
            </goals>
            <phase>verify</phase>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

</project>
